import i18nConfig from '@/i18nConfig';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import { dir } from 'i18next';
import Navbare from '@/components/Navbare';
import Footer from '@/components/Footer';
import Provider from '@/utils/reactQueryClient';
// import { QueryClientProvider } from '@tanstack/react-query';
// import { reactQueryClient } from '../../utils/reactQueryClient';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <Provider>
          <div>
            <Navbare />
            {children}
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}

export default RootLayout;
