import i18nConfig from '@/i18nConfig';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

import { dir } from 'i18next';
import Navbare from '@/components/Navbare';
import Footer from '@/components/Footer';
import Provider from '@/utils/reactQueryClient';
import DarkModeProviders from '@/utils/darkModeProviders';
import TranslationsProvider from '@/components/TranslationsProvider';
import initTranslations from '../i18n';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

async function RootLayout({
  children,
  params: { locale }
}: {
  children: ReactNode;
  params: { locale: string };
}) {
  const i18nNamespaces = ['home'];

  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang={locale} dir={dir(locale)} suppressHydrationWarning>
      <body className={inter.className}>
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locale}
          resources={resources}>
          <Provider>
            <DarkModeProviders>
              <Navbare />
              <div className="w-full h-screen">{children}</div>
              <Footer />
            </DarkModeProviders>
          </Provider>
        </TranslationsProvider>
      </body>
    </html>
  );
}

export default RootLayout;
